# Generated by Django 2.2.5 on 2022-08-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingroom',
            name='room',
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='room',
            field=models.ManyToManyField(null=True, to='hotel.Room'),
        ),
    ]
