# Generated by Django 2.2.5 on 2022-08-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20220831_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='room',
            field=models.ManyToManyField(to='hotel.Room'),
        ),
    ]
