# Generated by Django 2.2.5 on 2022-08-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20220831_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='room',
            field=models.ManyToManyField(null=True, to='hotel.Room'),
        ),
    ]
