# Generated by Django 2.2.5 on 2022-08-31 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20220831_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingroom',
            name='room',
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Room'),
        ),
    ]
