# Generated by Django 2.2.5 on 2022-09-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20220831_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
