# Generated by Django 2.2.5 on 2022-09-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_stafftask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafftask',
            old_name='Task',
            new_name='task',
        ),
    ]
