# Generated by Django 2.2.5 on 2022-09-02 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20220902_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.RemoveField(
            model_name='roomnumber',
            name='available',
        ),
        migrations.AddField(
            model_name='roomnumber',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Room'),
        ),
    ]
