# Generated by Django 2.2.5 on 2022-09-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20220903_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomnumber',
            name='room_number',
            field=models.IntegerField(unique=True),
        ),
    ]
