# Generated by Django 2.2.5 on 2022-09-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20220903_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomnumber',
            name='Check_out',
        ),
        migrations.RemoveField(
            model_name='roomnumber',
            name='check_in',
        ),
    ]
