# Generated by Django 2.2.5 on 2022-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20220903_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.CharField(max_length=10000),
        ),
    ]
