# Generated by Django 2.2.5 on 2022-09-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20220903_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='total_bill',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_On_Card', models.CharField(max_length=50)),
                ('Credit_Card_Number', models.CharField(max_length=12)),
                ('Exp_Month', models.CharField(max_length=2)),
                ('Exp_Year', models.CharField(max_length=4)),
                ('CVV', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.UserProfiles')),
            ],
        ),
    ]
