# Generated by Django 2.2.5 on 2022-09-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20220903_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='total_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
