# Generated by Django 2.2.5 on 2022-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20220903_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='need_approve',
            field=models.BooleanField(default=True),
        ),
    ]
