# Generated by Django 2.2.5 on 2022-09-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_auto_20220904_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Staff'),
        ),
    ]
