# Generated by Django 2.2.5 on 2022-09-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_auto_20220904_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Ac-Single', 'Ac-Single'), ('Single', 'Single'), ('Deluex', 'Deluex'), ('King', 'King'), ('Queen', 'Queen'), ('Stduio', 'Stduio'), ('Hollywood-Twin-Room', 'Hollywood-Twin-Room'), ('Executive', 'Executive'), ('MiniSuite', 'MiniSuite'), ('PresidentialSuite', 'PresidentialSuite'), ('Apartments', 'Apartments'), ('ConnectingRooms', 'ConnectingRooms'), ('MurphyRooms', 'MurphyRooms'), ('Accessible', 'Accessible'), ('Cabana', 'Cabana'), ('Adjoining Rooms', 'AdjoiningRoom'), ('Villa', 'Villa'), ('ExecutiveRoom', 'ExecutiveRoom'), ('Non-SmokingRoom', 'Non-SmokingRoom')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stafftask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Staff'),
        ),
    ]
